name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: src/go.sum
      - name: Install go-winres
        run: go install github.com/tc-hib/go-winres@latest
      - name: Run build script
        run: dist/build_win.bat
        working-directory: .
