name: Build and Release for macOS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: src/go.sum
      
      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest
  
      - name: Install macOS dependencies
        run: |
          echo "Installing Xcode Command Line Tools..."
          sudo xcode-select --install || true
      
      - name: Download FFmpeg and FFprobe for macOS Intel
        run: |
          mkdir -p tools
          # Ensure 7-Zip is available
          brew install --quiet p7zip
          
          # Download FFmpeg binary (works on both Intel and ARM via Rosetta)
          curl -L -o ffmpeg.7z https://evermeet.cx/ffmpeg/getrelease/7z
          7z x ffmpeg.7z -otools/ -y
          
          # Download FFprobe binary from its correct, separate archive
          curl -L -o ffprobe.7z https://evermeet.cx/ffmpeg/getrelease/ffprobe/7z
          7z x ffprobe.7z -otools/ -y
          
          # Set executable permissions
          chmod +x tools/ffmpeg tools/ffprobe
          
      - name: Build and Package Application
        run: |
          cd src
          # Set CGO flags for macOS compatibility
          export CGO_CFLAGS="-mmacosx-version-min=10.12"
          export CGO_LDFLAGS="-mmacosx-version-min=10.12"
          # Build the application using fyne package (creates .app and .dmg)
          fyne package -os darwin -name "MetaRekordFixer" -icon assets/applogo.png
        
      - name: Manually create DMG and verify build
        run: |
          cd src
          if [ ! -d "MetaRekordFixer.app" ]; then
            echo "Build failed: MetaRekordFixer.app was not created."
            exit 1
          fi
          echo "MetaRekordFixer.app found. Creating DMG manually..."
          hdiutil create -verbose -volname "MetaRekordFixer" -srcfolder "MetaRekordFixer.app" -ov -format UDZO "MetaRekordFixer.dmg"
      
      - name: Rename Artifacts for Release
        run: |
          cd src
          mv MetaRekordFixer.dmg metarekordfixer-1.0.0-darwin-amd64.dmg     

      - name: Upload installer to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          gh release upload v1.0.0 "metarekordfixer-1.0.0-darwin-amd64.dmg" --clobber

  build-macos-arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: src/go.sum
      
      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Install macOS dependencies
        run: |
         echo "Installing Xcode Command Line Tools..."
         sudo xcode-select --install || true        
      
      - name: Download FFmpeg and FFprobe for macOS ARM
        run: |
          mkdir -p tools
          # Ensure 7-Zip is available
          brew install --quiet p7zip

          # Download FFmpeg binary (Intel build runs on ARM via Rosetta 2)
          curl -L -o ffmpeg.7z https://evermeet.cx/ffmpeg/getrelease/7z
          7z x ffmpeg.7z -otools/ -y
          
          # Download FFprobe binary from its correct, separate archive
          curl -L -o ffprobe.7z https://evermeet.cx/ffmpeg/getrelease/ffprobe/7z
          7z x ffprobe.7z -otools/ -y
          
          # Set executable permissions
          chmod +x tools/ffmpeg tools/ffprobe
          
      - name: Build and Package Application
        env:
          GOARCH: arm64
        run: |
          cd src
          # Set CGO flags for macOS compatibility
          export CGO_CFLAGS="-mmacosx-version-min=10.12"
          export CGO_LDFLAGS="-mmacosx-version-min=10.12"
          # Build the application using fyne package (creates .app and .dmg)
          fyne package -os darwin -name "MetaRekordFixer" -icon assets/applogo.png
        
      - name: Manually create DMG and verify build
        run: |
         cd src
         if [ ! -d "MetaRekordFixer.app" ]; then
           echo "Build failed: MetaRekordFixer.app was not created."
           exit 1
          fi
         echo "MetaRekordFixer.app found. Creating DMG manually..."
         hdiutil create -verbose -volname "MetaRekordFixer" -srcfolder "MetaRekordFixer.app" -ov -format UDZO "MetaRekordFixer.dmg"

      - name: Rename Artifacts for Release
        run: |
          cd src
          mv MetaRekordFixer.dmg metarekordfixer-1.0.0-darwin-arm64.dmg

      - name: Upload installer to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          gh release upload v1.0.0 "metarekordfixer-1.0.0-darwin-arm64.dmg" --clobber
