name: Build and Release for Windows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'
          cache: true
          cache-dependency-path: src/go.sum
      - name: Install go-winres
        run: go install github.com/tc-hib/go-winres@latest
      - name: Run build script
        run: dist/build_win.bat
        working-directory: .
      - name: Upload installer to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v1.0.0 "dist/release/1.0.0/metarekordfixer-1.0.0-win64-setup.exe" --clobber